#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_HISTORY 5
#define MAX_INPUT 100


/*
 * Each conversation turn stores one user message
 * and the response generated by the mock model.
 */
struct Conversation
{
    char input[MAX_INPUT];
    char response[MAX_INPUT];
};


/*
 * Calculator function.
 *
 * This function only supports:
 *     + addition
 *     - subtraction
 *     * multiplication
 *     / division
 *
 * Returns 1 if the calculation was successful.
 * Returns 0 if the operation is not supported.
 */
int calculator(double number1, char operator, double number2,
               double *result)
{
    if (operator == '+')
    {
        *result = number1 + number2;
        return 1;
    }

    if (operator == '-')
    {
        *result = number1 - number2;
        return 1;
    }

    if (operator == '*')
    {
        *result = number1 * number2;
        return 1;
    }

    if (operator == '/')
    {
        /*
         * Do not divide by zero.
         */
        if (number2 == 0)
        {
            return 0;
        }

        *result = number1 / number2;
        return 1;
    }

    /*
     * Any other operator is unsupported.
     */
    return 0;
}


/*
 * This function checks whether the input is a simple
 * mathematical expression.
 *
 * Supported format:
 *
 *     number operator number
 *
 * Examples:
 *
 *     5 + 3
 *     10 - 4
 *     6 * 7
 *     20 / 5
 *
 * Returns 1 if the input has this format.
 * Returns 0 otherwise.
 */
int is_expression(char input[])
{
    double number1;
    double number2;
    char operator;

    if (sscanf(input, "%lf %c %lf",
               &number1, &operator, &number2) == 3)
    {
        return 1;
    }

    return 0;
}


/*
 * This is our local mock model.
 *
 * It does NOT call an actual LLM.
 * It uses simple rules to decide what response to give.
 */
void mock_model(char input[],
                struct Conversation history[],
                int history_count,
                char response[])
{
    double number1;
    double number2;
    double result;

    char operator;

    /*
     * Rule 1:
     * Respond to messages containing "hello".
     */
    if (strstr(input, "hello") != NULL)
    {
        strcpy(response, "Hello! Nice to meet you.");
        return;
    }


    /*
     * Rule 2:
     *
     * Check for a direct mathematical expression.
     *
     * Example:
     *     5 + 3
     */
    if (is_expression(input))
    {
        sscanf(input, "%lf %c %lf",
               &number1, &operator, &number2);

        /*
         * Check for division by zero separately so that
         * we can give the user a useful error message.
         */
        if (operator == '/' && number2 == 0)
        {
            sprintf(response,
                    "The operation '%s' is not supported because division by zero is not allowed.",
                    input);
            return;
        }

        /*
         * Call the calculator.
         */
        if (calculator(number1, operator, number2, &result))
        {
            sprintf(response,
                    "The answer is %.2f",
                    result);
        }
        else
        {
            /*
             * The expression contains an unsupported
             * mathematical operation.
             */
            sprintf(response,
                    "The operation '%s' is not supported.",
                    input);
        }

        return;
    }


    /*
     * Rule 3:
     *
     * Allow the calculator to be requested using words.
     *
     * Supported examples:
     *
     *     add 5 3
     *     subtract 10 4
     *     multiply 6 7
     *     divide 20 5
     */
    if (sscanf(input, "add %lf %lf", &number1, &number2) == 2)
    {
        operator = '+';
    }
    else if (sscanf(input, "subtract %lf %lf",
                    &number1, &number2) == 2)
    {
        operator = '-';
    }
    else if (sscanf(input, "multiply %lf %lf",
                    &number1, &number2) == 2)
    {
        operator = '*';
    }
    else if (sscanf(input, "divide %lf %lf",
                    &number1, &number2) == 2)
    {
        operator = '/';
    }
    else
    {
        /*
         * No supported calculation was requested.
         * Give the simple default mock-model response.
         */
        sprintf(response,
                "I received your message: %s",
                input);

        return;
    }


    /*
     * Check for division by zero when the user
     * requested division by name.
     */
    if (operator == '/' && number2 == 0)
    {
        sprintf(response,
                "The operation '%s' is not supported because division by zero is not allowed.",
                input);
        return;
    }


    /*
     * Call the calculator for the requested operation.
     */
    if (calculator(number1, operator, number2, &result))
    {
        sprintf(response,
                "The answer is %.2f",
                result);
    }
    else
    {
        /*
         * This should only happen if an unsupported
         * operator somehow reaches the calculator.
         */
        sprintf(response,
                "The operation '%s' is not supported.",
                input);
    }
}


/*
 * Main program.
 */
int main(void)
{
    char input[MAX_INPUT];
    char response[MAX_INPUT];

    /*
     * Allocate memory for the conversation history.
     *
     * malloc() is used so that we can explicitly check
     * whether memory allocation was successful.
     */
    struct Conversation *history;

    history = malloc(MAX_HISTORY * sizeof(struct Conversation));

    /*
     * Check whether malloc() failed.
     */
    if (history == NULL)
    {
        printf("Error: Could not allocate memory for conversation history.\n");
        return 1;
    }


    /*
     * Number of conversation turns currently stored.
     */
    int history_count = 0;


    /*
     * Main input loop.
     */
    while (1)
    {
        /*
         * Prompt the user.
         */
        printf("You: ");

        /*
         * Read input using fgets().
         *
         * fgets() returns NULL if it fails.
         */
        if (fgets(input, sizeof(input), stdin) == NULL)
        {
            /*
             * Handle an input failure without crashing.
             */
            printf("Error: Failed to read input.\n");
            break;
        }


        /*
         * Remove the newline character added by fgets().
         */
        input[strcspn(input, "\n")] = '\0';


        /*
         * Check whether the user wants to exit.
         */
        if (strcmp(input, "exit") == 0)
        {
            break;
        }


        /*
         * If the history is already full, remove the
         * oldest conversation turn.
         */
        if (history_count == MAX_HISTORY)
        {
            int i;

            for (i = 0; i < MAX_HISTORY - 1; i++)
            {
                history[i] = history[i + 1];
            }

            history_count--;
        }


        /*
         * Store the user's input in the newest history entry.
         */
        strcpy(history[history_count].input, input);


        /*
         * Give the input and history to the mock model.
         */
        mock_model(input,
                   history,
                   history_count,
                   response);


        /*
         * Print the model's response.
         */
        printf("Model: %s\n", response);


        /*
         * Store the model's response in the conversation history.
         */
        strcpy(history[history_count].response, response);


        /*
         * Increase the number of stored conversation turns.
         */
        history_count++;
    }


    /*
     * Clean up the dynamically allocated memory.
     */
    free(history);
    history = NULL;


    /*
     * End the program normally.
     */
    printf("Program ended.\n");

    return 0;
}

